packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  # Dev tooling
  eslint: ^9.19.0
  prettier: ^3.4.2
  tailwindcss: ^4.1.11
  typescript: ^5.7.3

  # Misc
  zod: ^4.0.5
  zod-openapi: ^5.2.0
  "@t3-oss/env-nextjs": ^0.13.8
  ai: ^4.3.19

  # Tanstack & tRPC
  "@tanstack/react-query": ^5.83.0
  "@trpc/client": ^11.4.3
  "@trpc/tanstack-react-query": ^11.4.3
  "@trpc/server": ^11.4.3

catalogs:
  react19:
    react: 19.1.0
    react-dom: 19.1.0
    "@types/react": ^19.1.2
    "@types/react-dom": ^19.1.2
